basePath: /
host: localhost:8080
info:
  contact: {}
  description: This is the API server for Chirpy application
  title: Chirpy API
  version: "1.0"
paths:
  /admin/metrics:
    get:
      description: Returns an HTML page showing the number of times Chirpy has been
        visited
      operationId: get-metrics
      produces:
      - text/html
      responses:
        "200":
          description: HTML content displaying the visit count
          schema:
            type: string
      summary: Get Metrics
      tags:
      - metrics
  /api/healthz:
    get:
      consumes:
      - application/json
      description: Returns OK if the server is healthy
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Health check endpoint
      tags:
      - health
swagger: "2.0"
